# This is a basic workflow to help you get started with Actions

name: Deploy to ESP32

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installing platformio
        run: pip3 install -U platformio
      # Runs a set of commands using the runners shell
      - name: Build for ESP32
        run: pio run
      - name: Uploading a firmware to ESP32
        run: > 
          curl --http1.1 -# -v 
          -H 'Accept: */*' 
          -H 'Accept-Encoding: gzip, deflate' 
          -H 'Connection: keep-alive' 
          -F "MD5="$(md5sum .pio/build/esp32dev/firmware.bin | cut -d ' ' -f 4)"" 
          -F 'firmware=@.pio/build/esp32dev/firmware.bin' 'http://guberkray.myftp.org:8096/update'
